@ImproveU_backend_HostAddress = http://localhost:32770

GET {{ImproveU_backend_HostAddress}}/api/usuarios/
Accept: application/json

###

DELETE {{ImproveU_backend_HostAddress}}/api/usuarios/2
Accept: application/json

###
