using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ImproveU_backend.Migrations.NegocioContext
{
    /// <inheritdoc />
    public partial class SeedListaExericicios : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"INSERT INTO public.exercicios (nome) VALUES
                                    ('Abdominal Classico'),
                                    ('Abdominal Inclinado Apoiado'),
                                    ('Abdominal Jack Knife'),
                                    ('Abdominal Lateral'),
                                    ('Abdominal Lateral Alternado'),
                                    ('Abdominal Modawalk'),
                                    ('Aberturas'),
                                    ('Aberturas Cabos'),
                                    ('Aberturas Cabos Declinado'),
                                    ('Aberturas Inclinadas'),
                                    ('Aberturas invertidas'),
                                    ('Abdutores em máquina'),
                                    ('Agachamento'),
                                    ('Agachamento búlgaro'),
                                    ('Agachamento com halteres'),
                                    ('Agachamento com um halter'),
                                    ('Agachamento com uma perna'),
                                    ('Agachamento frontal'),
                                    ('Agachamento Hack'),
                                    ('Agachamento sumo'),
                                    ('Arnold Press'),
                                    ('Bicep Cabos'),
                                    ('Bicep Concentrado Banco'),
                                    ('Bicep Halter Concentrado'),
                                    ('Bícep concentrado na máquina'),
                                    ('Curl Bicep Barra'),
                                    ('Curl Bicep Halter'),
                                    ('Curl Martelo'),
                                    ('Curl de bícep com halter e banda de resistência'),
                                    ('Curl de bícep com press de ombro'),
                                    ('Curl de bíceps inclinado'),
                                    ('Drag curl com barra'),
                                    ('Elevação das pernas em suspensão'),
                                    ('Elevação Pernas'),
                                    ('Elevação Pernas Parcial'),
                                    ('Elevação de gémeos em máquina sentado'),
                                    ('Elevação de gémeos em pé com halteres'),
                                    ('Elevações'),
                                    ('Elevações com peso e pega curta'),
                                    ('Elevações com pega larga'),
                                    ('Encolhimento FS'),
                                    ('Extensao Perna'),
                                    ('Extensao Tricep Maquina'),
                                    ('Extensão de gémeos em máquina'),
                                    ('Extensão deitado com halteres'),
                                    ('Extensão lateral com halter'),
                                    ('Farmer''s Walk'),
                                    ('Frontais'),
                                    ('Fundos'),
                                    ('Fundos com peso'),
                                    ('Gémeos na prensa'),
                                    ('Hiperextensões'),
                                    ('Hip Thrust'),
                                    ('Leg Curl'),
                                    ('Leg Extension'),
                                    ('Lunges com barra'),
                                    ('Lunges com halteres'),
                                    ('Peck-Deck'),
                                    ('Peso morto com halteres'),
                                    ('Peso morto com halteres e pernas semi esticadas'),
                                    ('Peso morto com trap bar'),
                                    ('Peso morto romeno com barra'),
                                    ('Peso morto romeno com halteres'),
                                    ('Peso morto sumo'),
                                    ('Ponte para glúteos'),
                                    ('Prancha'),
                                    ('Prancha Alternada'),
                                    ('Prancha com Elevação'),
                                    ('Press com halteres e pega curta'),
                                    ('Press de ombros unilateral'),
                                    ('Press Militar'),
                                    ('Press Ombro Halter'),
                                    ('Prensa'),
                                    ('Pulldown Maquina'),
                                    ('Pullover com halter'),
                                    ('Puxada com cabos inclinado'),
                                    ('Puxada frontal'),
                                    ('Remada Alta Maquina'),
                                    ('Remada com Barra'),
                                    ('Remada com Halter'),
                                    ('Remada Sentada Maquina'),
                                    ('Remada T'),
                                    ('Rotação Lateral'),
                                    ('Rotação Pernas'),
                                    ('Shrugs com barra'),
                                    ('Step Up com halteres'),
                                    ('Supino Declinado'),
                                    ('Supino Inclinado'),
                                    ('Supino Plano'),
                                    ('Swings'),
                                    ('Thrusters'),
                                    ('Tricep a Testa Barra'),
                                    ('V-Up');
                                ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DELETE FROM public.exercicios WHERE nome IN (
                                    'Abdominal Classico',
                                    'Abdominal Inclinado Apoiado',
                                    'Abdominal Jack Knife',
                                    'Abdominal Lateral',
                                    'Abdominal Lateral Alternado',
                                    'Abdominal Modawalk',
                                    'Aberturas',
                                    'Aberturas Cabos',
                                    'Aberturas Cabos Declinado',
                                    'Aberturas Inclinadas',
                                    'Aberturas invertidas',
                                    'Abdutores em máquina',
                                    'Agachamento',
                                    'Agachamento búlgaro',
                                    'Agachamento com halteres',
                                    'Agachamento com um halter',
                                    'Agachamento com uma perna',
                                    'Agachamento frontal',
                                    'Agachamento Hack',
                                    'Agachamento sumo',
                                    'Arnold Press',
                                    'Bicep Cabos',
                                    'Bicep Concentrado Banco',
                                    'Bicep Halter Concentrado',
                                    'Bícep concentrado na máquina',
                                    'Curl Bicep Barra',
                                    'Curl Bicep Halter',
                                    'Curl Martelo',
                                    'Curl de bícep com halter e banda de resistência',
                                    'Curl de bícep com press de ombro',
                                    'Curl de bíceps inclinado',
                                    'Drag curl com barra',
                                    'Elevação das pernas em suspensão',
                                    'Elevação Pernas',
                                    'Elevação Pernas Parcial',
                                    'Elevação de gémeos em máquina sentado',
                                    'Elevação de gémeos em pé com halteres',
                                    'Elevações',
                                    'Elevações com peso e pega curta',
                                    'Elevações com pega larga',
                                    'Encolhimento FS',
                                    'Extensao Perna',
                                    'Extensao Tricep Maquina',
                                    'Extensão de gémeos em máquina',
                                    'Extensão deitado com halteres',
                                    'Extensão lateral com halter',
                                    'Farmer''s Walk',
                                    'Frontais',
                                    'Fundos',
                                    'Fundos com peso',
                                    'Gémeos na prensa',
                                    'Hiperextensões',
                                    'Hip Thrust',
                                    'Leg Curl',
                                    'Leg Extension',
                                    'Lunges com barra',
                                    'Lunges com halteres',
                                    'Peck-Deck',
                                    'Peso morto com halteres',
                                    'Peso morto com halteres e pernas semi esticadas',
                                    'Peso morto com trap bar',
                                    'Peso morto romeno com barra',
                                    'Peso morto romeno com halteres',
                                    'Peso morto sumo',
                                    'Ponte para glúteos',
                                    'Prancha',
                                    'Prancha Alternada',
                                    'Prancha com Elevação',
                                    'Press com halteres e pega curta',
                                    'Press de ombros unilateral',
                                    'Press Militar',
                                    'Press Ombro Halter',
                                    'Prensa',
                                    'Pulldown Maquina',
                                    'Pullover com halter',
                                    'Puxada com cabos inclinado',
                                    'Puxada frontal',
                                    'Remada Alta Maquina',
                                    'Remada com Barra',
                                    'Remada com Halter',
                                    'Remada Sentada Maquina',
                                    'Remada T',
                                    'Rotação Lateral',
                                    'Rotação Pernas',
                                    'Shrugs com barra',
                                    'Step Up com halteres',
                                    'Supino Declinado',
                                    'Supino Inclinado',
                                    'Supino Plano',
                                    'Swings',
                                    'Thrusters',
                                    'Tricep a Testa Barra',
                                    'V-Up'
                                    );");
        }
    }
}
